### ISSUE TITLE
Distributed package seems to be referring to the source of the jsondiffpatch

### ISSUE THREAD

**Issue by unandyala** [schnerd/jsondiffpatch-arrays-by-hash#1]
I am seeing the below error while using this package

`Error: Cannot find module 'jsondiffpatch/src/contexts/diff' `

Thanks

**Comment by schnerd** [comment]
Thanks for the heads up, looking into it.

**Comment by schnerd** [comment]
This plugin unfortunately referenced some parts of jsondiffpatch that were not part of the public API (hence the /src imports), and it seems like newer releases of jsondiffpatch changed the build strategy so these modules are no longer available.

Accordingly, this package will need to be fixed or rewritten, possibly asking the jsondiffpatch maintainers to export the necessary modules. Unclear how long this will take.

In the meantime, you can downgrade jsondiffpatch to <= v0.2.5 if you absolutely need to use this plugin.
```
npm install -s jsondiffpatch@v0.2.5
```

**Comment by schnerd** [comment]
Seeking guidance in jsondiffpatch repo: https://github.com/benjamine/jsondiffpatch/issues/285

**Comment by AesSedai** [comment]
@schnerd I was able to get your plugin working again on the newest version of jsonpatchdiff (0.4.1) by changing the `new DiffContext | PatchContext  | ReverseContext ` to instead be `new context.constructor` (solves the issue of needing to import those contexts), and just copying in the `lcs`, `backtrack`, `lengthMatrix`, and `defaultMatch` functions from the jsonpatchdiff repo. 

Copying the `lcs` + `lcs` helpers isn't precisely pretty, but it certainly works.

**Comment by schnerd** [comment]
Fixed with 1.0.3, thanks @AesSedai
